version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - mvn package
      - mv target/Card-0.0.1-SNAPSHOT.war Card-0.0.1-SNAPSHOT.war
  artifacts:
    files: '**/*'
    base-directory: target/Card-0.0.1-SNAPSHOT